apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    name: backend
    project: expense
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      name: backend
      project: expense
      tier: app
  template:
    metadata:
      labels:
        name: backend
        project: expense
        tier: app
    spec:
      containers:
        - name: backend
          image: kalyaneswarm/backend:{{ .Values.deployment.imageVersion}}
          envFrom:
            - configMapRef:
                name: backend