apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    name: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: backend
      project: expense
      tier: app
  template:
    metadata:
      labels:
        name: backend
        project: expense
        tier: app
    spec:
      containers:
        - name: backend
          image: kalyaneswarm/backend:v1.0
          envFrom:
            - configMapRef:
                name: backend

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense   
spec:
  selector:
    name: backend
    project: expense
    tier: app 
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 # Target port

---


              
        

    
  