apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense   
spec:
  selector:
    name: backend
    project: expense
    tier: app 
  ports:
  - protocol: TCP
    port: {{ .Values.service.serviceport }} #service-port
    targetPort: {{.Values.service.targetport }} # Target port