apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    name: abc
    project : testtt
  annotations:
    github: https://github.com/kalyaneswar/03-K8-Practice
    
spec:
  containers:
    - name: tomcat
      image: tomcat
      ports:
      - containerPort: 8080
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80