apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    name: abc
    project : testtt
  annotations:
    github: https://github.com/kalyaneswar/03-K8-Practice

spec:
  containers:
    # - name: tomcat
    #   image: tomcat
    #   ports:
    #   - containerPort: 8080
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      env:
        - name: k8
          value: kubenetes
        - name: owner
          value: kalyaN
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"