apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: expense
  labels:
    name: mysql
    project: expense
    tier: db   
spec:
  type: ClusterIP 
  selector:
    name: mysql
    project: expense
    tier: db 
  ports:
    - port: 3306 #serviceport
      targetPort: 3306

    
    


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    name: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      name: mysql
      project: expense
      tier: db
  template:
    metadata:
      name: mysql-dev
      labels:
        name: mysql
        project: expense
        tier: db
    spec:
      containers:
        - name: mysql-db
          image: kalyaneswarm/mysql:v1.0
              
        

    
  