kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-07e3179543e82a35d
  directoryPerms: "700"
  basePath: "/expense" # optional

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-1
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-07e3179543e82a35d
  directoryPerms: "700"
  basePath: "/despense" # optional
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-dynamic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-dynamic-1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-1
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app-dynamic
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim-dynamic

---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app-dynamic-1
spec:
  containers:
    - name: app-1
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim-dynamic-1