apiVersion: v1
kind: Service
metadata:
  name: expense-svc
  labels:
    project: expense
    environment: dev
    tier: mysql
spec:
  ports:
    - port: 3306
      # targetPort: 3306 as container port is often referred to as the target port.
  selector:
    project: expense
    environment: dev
    tier: mysql
  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-deployment
  labels:
    project: expense
    environment: dev
    tier: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
      tier: mysql
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: kalyaneswarm/mysql:v1.0
        ports:
        - containerPort: 3306   
