apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
  labels:
    name: mysql
    project: expense
    tier: db   
spec:
  selector:
    name: mysql
    project: expense
    tier: db 
  ports:
    - protocol: TCP
      port: {{ .Values.service.serviceport }} #serviceport
      targetPort: {{ .Values.service.targetport }} 