apiVersion: v1
kind: Pod
metadata:
  name: kalyan-nginx-pod
  namespace: kalyan
  labels:
    app: kalyan-app
    use: world
spec:
  containers:
    - name: nginx-service
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: KINGNAME
          value: Kalyan
        - name: QUEEN
          value: Sam
    
  