# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: kalyan-configmap
data:
  git_url: https://github.com/kalyaneswar/03-K8-Practice.git
  facebook_profile: kalyanprice.facebook.com
#
---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: kalyan-secret
data:
  username: "YWRtaW4K"
  password: "YWRtaW4xMjMK"

---
# Service |

# apiVersion: v1
# kind: Service
# metadata:
#   name: kalyan-service
# spec:
#   selector:
#     app: kalyan-app
#     use: world
#   ports:
#     - port: 80
#       targetPort: 80
    


---
# Pod
apiVersion: v1
kind: Pod
metadata:
  name: kalyan-nginx-pod
  namespace: kalyan
  labels:
    app: kalyan-app
    use: world
spec:
  containers:
    - name: nginx-service
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: KINGNAME
          value: Kalyan
        - name: QUEEN
          value: Sam
      envFrom:
        - configMapRef:
            name: kalyan-configmap
        - secretRef:
            name: kalyan-secret
  