apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: expense-svc
  namespace: expense
spec:
  selector:
    project: expense
    environment: dev
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: expense
  labels:
    project: expense
    environment: dev
    tier: backend
spec:
  selector:
    matchLabels:
      project: expense
      environment: dev
      tier: backend
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        tier: backend
    spec:
      containers:
        - name: backend
          image: kalyaneswarm/backend:v1.0
          envFrom:
            - configMapRef:
                name: backend