apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-static
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-e8a95a42

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-static
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: efs-sc
  volumeName: efs-pv-static
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: efs-static
spec:
  containers:
  - name: efs-static
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim-static