apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 11Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0d09833a50beec81d