
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    name: backend
    project: expense
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: backend
      project: expense
      tier: backend
  template:
    metadata:
      name: backend-dev
      labels:
        name: backend
        project: expense
        tier: backend
    spec:
      containers:
        - name: backend
          image: joindevops/backend:v1.0
          envFrom:
            - configMapRef:
                name: backend

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense   
spec:
  type: ClusterIP 
  selector:
    name: backend
    project: expense
    tier: backend 
  ports:
    - port: 8080 #serviceport
      targetPort: 8080

---


              
        

    
  