apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql-db
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    name: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: backend
      project: expense
      tier: app
  template:
    metadata:
      labels:
        name: backend
        project: expense
        tier: app
    spec:
      containers:
        - name: backend
          image: kalyaneswarm/backend:v1.0
          envFrom:
            - configMapRef:
                name: backend

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense   
spec:
  type: ClusterIP 
  selector:
    name: backend
    project: expense
    tier: app 
  ports:
    - port: 8080 

---


              
        

    
  